spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center?serverTimezone=Asia/Shanghai
    username: root
    password: llh112358
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0

server:
  port: 8080
  servlet:
    context-path: /api